const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const context=await browser.newContext({viewport:{width:1365,height:900},locale:'pt-BR'});
 const page=await context.newPage();
 const erros=[]; page.on('pageerror',e=>erros.push(e.message));
 await page.goto('http://localhost:8081');
 await page.screenshot({path:'tmp/inicio-desktop.png',fullPage:true});
 await page.getByRole('link',{name:'Entrar',exact:true}).click();
 await page.getByLabel('E-mail',{exact:true}).fill('dono@example.test');
 await page.getByLabel('Senha',{exact:true}).fill('AgendaTeste123!');
 await page.getByRole('button',{name:'Entrar',exact:true}).click();
 await page.waitForURL('**/proprietario/quadras');
 await page.screenshot({path:'tmp/quadras-desktop.png',fullPage:true});
 await page.getByRole('link',{name:'Disponibilidades',exact:true}).first().click();
 await page.screenshot({path:'tmp/agenda-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Sair',exact:true}).click();
 await page.getByLabel('E-mail',{exact:true}).fill('cliente@example.test');
 await page.getByLabel('Senha',{exact:true}).fill('AgendaTeste123!');
 await page.getByRole('button',{name:'Entrar',exact:true}).click();
 await page.waitForURL('**/cliente/quadras');
 await page.getByRole('link',{name:'Ver horários'}).first().click();
 await page.getByRole('button',{name:'Escolher',exact:true}).last().click();
 await page.getByLabel('Início',{exact:true}).fill('16:00');
 await page.getByLabel('Fim',{exact:true}).fill('17:00');
 await page.getByRole('button',{name:'Confirmar reserva',exact:true}).click();
 await page.waitForURL('**/reservas');
 await page.getByText('Reserva confirmada! Confira os detalhes abaixo.').waitFor();
 await page.screenshot({path:'tmp/reservas-desktop.png',fullPage:true});
 page.on('dialog',d=>d.accept());
 await page.getByRole('button',{name:'Cancelar reserva',exact:true}).last().click();
 await page.getByText('Reserva cancelada. O histórico foi preservado.').waitFor();
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,locale:'pt-BR'});
 const tela=await mobile.newPage();
 await tela.goto('http://localhost:8081');
 await tela.screenshot({path:'tmp/inicio-mobile.png',fullPage:true});
 if(await tela.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)) throw new Error('Página inicial com rolagem horizontal');
 await tela.goto('http://localhost:8081/cadastro/cliente');
 await tela.screenshot({path:'tmp/cadastro-mobile.png',fullPage:true});
 if(await tela.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)) throw new Error('Cadastro com rolagem horizontal');
 if(erros.length) throw new Error(erros.join('\n'));
 fs.writeFileSync('tmp/resultado-navegador.json',JSON.stringify({resultado:'aprovado',errosJavaScript:erros,fluxos:['login proprietário','agenda','logout','login cliente','escolher horário','reservar','cancelar','layout 390px']},null,2));
 await browser.close();
 console.log('Fluxos reais de navegador aprovados; capturas salvas.');
})().catch(e=>{console.error(e);process.exitCode=1});
